### ISSUE TITLE
http4s milestone plan

### ISSUE THREAD

**Issue by rossabaker** [http4s/http4s-fs2-data#49]
Is this repo going to track http4s-1.0 milestones, or just stick to http4s-0.23 until 1.0 is fully cooked?  It's cool either way, but I'd like to set expectations on https://github.com/http4s/http4s/discussions/6903.

**Comment by ybasket** [comment]
Sorry, I had my GitHub notifications set up wrong and didn't notice this issue until now. I'll see whether I can get this repo to compile against 1.0 without bigger problems/changes and if so, publish milestones for 1.0.

**Comment by ybasket** [comment]
Worked fine and is released as `1.0.0-M39`, left a comment on https://github.com/http4s/http4s/discussions/6903 to reflect this.
